export interface Talent {
  id: number;
  name: string;
  description: string;
}

export const TALENTS: Talent[] = [
  { id: 1, name: 'Designing Ideals', description: 'You excel at creating systems that embody high standards, like an architect drafting the blueprint of a groundbreaking sustainable building.' },
  { id: 2, name: 'Advocating Fairness', description: 'You are passionate about promoting justice, like a human rights lawyer fighting for equal rights in court.' },
  { id: 3, name: 'Seeking Improvements', description: 'You thrive in refining processes, like a quality control specialist enhancing production methods for efficiency.' },
  { id: 4, name: 'Mastering Precision', description: 'You love achieving flawless execution, akin to a watchmaker assembling intricate timepieces with exactness.' },
  { id: 5, name: 'Upholding Ethics', description: 'You are committed to acting ethically, much like a journalist dedicated to reporting unbiased truths.' },
  { id: 6, name: 'Maintaining Order', description: 'You find satisfaction in organizing systems, like a librarian cataloging books for easy access.' },
  { id: 7, name: 'Standing for Righteousness', description: 'You are unafraid to stand up for what is right, like an activist campaigning against social injustices.' },
  { id: 8, name: 'Building Structures', description: 'You thrive in creating order from chaos, like a project manager streamlining a complex project plan.' },
  { id: 9, name: 'Crafting Visions', description: 'You find joy in setting lofty goals, similar to a CEO outlining a visionary business strategy.' },
  { id: 10, name: 'Assisting Empathetically', description: 'You excel in helping others through empathy, like a nurse providing compassionate care to patients.' },
  { id: 11, name: 'Building Harmonious Relationships', description: 'You naturally build harmonious relationships, like a diplomat fostering peace between nations.' },
  { id: 12, name: 'Offering Service', description: 'You love offering your service to those in need, akin to a humanitarian delivering aid in crisis zones.' },
  { id: 13, name: 'Providing Emotional Support', description: 'You find fulfillment in supporting others emotionally, like a counselor guiding clients through challenges.' },
  { id: 14, name: 'Anticipating Needs', description: 'You excel at foreseeing others\' needs, like a personal assistant preparing everything before it\'s requested.' },
  { id: 15, name: 'Cultivating Community', description: 'You enjoy fostering a sense of community, akin to a community organizer planning local events.' },
  { id: 16, name: 'Showering Generosity', description: 'You find joy in acts of generosity, like a philanthropist funding educational scholarships.' },
  { id: 17, name: 'Communicating Heartfelt Messages', description: 'You have a knack for sincere expression, like a writer crafting a moving memoir.' },
  { id: 18, name: 'Giving Affection', description: 'You thrive in sharing love and warmth, like a caregiver providing comfort to those in need.' },
  { id: 19, name: 'Setting Goals', description: 'You love establishing and reaching ambitious targets, like an athlete training to win a gold medal.' },
  { id: 20, name: 'Organizing Efficiently', description: 'You thrive in arranging tasks effectively, like a logistics manager coordinating timely deliveries.' },
  { id: 21, name: 'Chasing Success', description: 'You are energized by pursuing achievements, similar to an entrepreneur launching a successful startup.' },
  { id: 22, name: 'Crafting Images', description: 'You excel at creating impressive personal or brand images, akin to a marketing professional building a strong brand identity.' },
  { id: 23, name: 'Mastering Performances', description: 'You have a knack for delivering outstanding performances, like an actor captivating an audience on stage.' },
  { id: 24, name: 'Maximizing Potential', description: 'You derive satisfaction from fully developing abilities, like a coach helping athletes reach peak performance.' },
  { id: 25, name: 'Striving for Excellence', description: 'You are committed to achieving excellence, similar to a chef perfecting a signature dish.' },
  { id: 26, name: 'Nurturing Competitiveness', description: 'You thrive on healthy competition, like a salesperson aiming to top sales charts.' },
  { id: 27, name: 'Seeking Recognition', description: 'You find fulfillment in being acknowledged for your accomplishments, like a researcher receiving a prestigious award.' },
  { id: 28, name: 'Experiencing Deep Emotions', description: 'You embrace profound emotions, similar to an artist conveying feelings through their work.' },
  { id: 29, name: 'Preserving Authenticity', description: 'You value staying true to yourself, akin to an indie musician maintaining their unique sound.' },
  { id: 30, name: 'Appreciating Aesthetics', description: 'You find joy in the beauty of design, like an interior designer creating harmonious spaces.' },
  { id: 31, name: 'Exploring Inner Self', description: 'You delve into self-discovery, like a philosopher reflecting on personal identity.' },
  { id: 32, name: 'Creating Originality', description: 'You thrive on producing original work, like an inventor developing a groundbreaking gadget.' },
  { id: 33, name: 'Romanticizing Life', description: 'You enjoy seeing life through a poetic lens, similar to a novelist weaving tales of epic adventures.' },
  { id: 34, name: 'Craving Intensity', description: 'You have a natural desire for passionate experiences, like a filmmaker crafting emotionally charged scenes.' },
  { id: 35, name: 'Seeking Beauty', description: 'You derive satisfaction from finding beauty in the world, like a photographer capturing breathtaking images.' },
  { id: 36, name: 'Seeking Depth', description: 'You are driven to pursue profound experiences, akin to a deep-sea explorer venturing into uncharted waters.' },
  { id: 37, name: 'Questing for Knowledge', description: 'You delight in exploring new domains, like a scientist researching unexplored phenomena.' },
  { id: 38, name: 'Unraveling Secrets', description: 'You decipher complex information, much like a detective solving intricate mysteries.' },
  { id: 39, name: 'Constructing Thought Systems', description: 'You enjoy building comprehensive ideas, similar to a theorist developing new frameworks.' },
  { id: 40, name: 'Architecting Innovations', description: 'You build groundbreaking solutions to complex problems, much like an engineer designing cutting-edge technology.' },
  { id: 41, name: 'Cultivating Wisdom', description: 'You focus on gaining wisdom, akin to a scholar dedicated to lifelong learning.' },
  { id: 42, name: 'Refining Intellect', description: 'You relish honing your understanding, similar to a chess grandmaster strategizing plays.' },
  { id: 43, name: 'Learning Independently', description: 'You thrive in self-directed learning, like an autodidact mastering a new skill.' },
  { id: 44, name: 'Deepening Observations', description: 'You enhance understanding through keen observation, much like a biologist studying ecosystems.' },
  { id: 45, name: 'Synthesizing Understanding', description: 'You excel at distilling complex concepts into clear insights, like a teacher explaining difficult subjects.' },
  { id: 46, name: 'Building Trust', description: 'You enjoy fostering trust, like a counselor establishing rapport with clients.' },
  { id: 47, name: 'Predicting Problems', description: 'You excel at anticipating potential issues, akin to a risk manager identifying future challenges.' },
  { id: 48, name: 'Providing Security', description: 'You find fulfillment in ensuring safety, similar to a cybersecurity expert protecting data.' },
  { id: 49, name: 'Being Reliable', description: 'You thrive in being dependable, akin to a trusted colleague who delivers consistently.' },
  { id: 50, name: 'Seeking Guidance', description: 'You value learning from others, like an apprentice absorbing knowledge from a master craftsman.' },
  { id: 51, name: 'Craving Assurance', description: 'You seek affirmation, like an author appreciating feedback from readers.' },
  { id: 52, name: 'Navigating Systems', description: 'You excel in maneuvering through complex structures, akin to a policy analyst understanding regulatory landscapes.' },
  { id: 53, name: 'Assessing Danger', description: 'You have a knack for evaluating risks, like a safety inspector identifying workplace hazards.' },
  { id: 54, name: 'Upholding Loyalty', description: 'You are committed to being loyal, similar to a teammate supporting their group through challenges.' },
  { id: 55, name: 'Innovating in Uncharted Areas', description: 'You love exploring new ideas, like a tech entrepreneur pioneering novel technologies.' },
  { id: 56, name: 'Motivating with Positive Energy', description: 'You inspire others with enthusiasm, much like a motivational speaker energizing an audience.' },
  { id: 57, name: 'Diversifying Skill Sets', description: 'You thrive when learning varied skills, like a generalist adapting to multiple roles.' },
  { id: 58, name: 'Visioning Bold Ventures', description: 'You find joy in planning adventurous strategies, comparable to an executive entering new markets.' },
  { id: 59, name: 'Fostering a Joyful Workplace', description: 'You excel at creating vibrant work cultures, like an HR manager organizing team-building activities.' },
  { id: 60, name: 'Conceptualizing Innovative Solutions', description: 'Your imagination crafts fresh approaches, like a product designer developing a unique gadget.' },
  { id: 61, name: 'Facilitating Creative Brainstorms', description: 'You harness collective thinking for ideas, like a creative director leading brainstorming sessions.' },
  { id: 62, name: 'Incorporating Fun into Work', description: 'You blend enjoyment with tasks, similar to a teacher using games to engage students.' },
  { id: 63, name: 'Navigating Freelance Opportunities', description: 'You prefer project flexibility, akin to a freelancer choosing diverse assignments.' },
  { id: 64, name: 'Exercising Power', description: 'You confidently take charge, like a CEO making strategic decisions for growth.' },
  { id: 65, name: 'Maintaining Control', description: 'You thrive in guiding situations, akin to a conductor directing a symphony orchestra.' },
  { id: 66, name: 'Ensuring Justice', description: 'You are passionate about fairness, like a judge delivering impartial verdicts.' },
  { id: 67, name: 'Breaking Barriers', description: 'You enjoy challenging limitations, similar to an innovator disrupting traditional industries.' },
  { id: 68, name: 'Offering Protection', description: 'You are naturally protective, akin to a firefighter safeguarding the community.' },
  { id: 69, name: 'Making Decisions', description: 'You excel in making prompt decisions, like an emergency room doctor prioritizing patient care.' },
  { id: 70, name: 'Displaying Strength', description: 'You are open to demonstrating your capabilities, similar to an athlete showcasing skills in competition.' },
  { id: 71, name: 'Valuing Independence', description: 'You assert your autonomy, like a solo entrepreneur running their own business.' },
  { id: 72, name: 'Taking Leadership', description: 'You are a natural leader, like a captain guiding a team to victory.' },
  { id: 73, name: 'Creating Harmony', description: 'You love bringing people together, like a mediator resolving workplace conflicts.' },
  { id: 74, name: 'Offering Understanding', description: 'You excel at empathy, akin to a therapist connecting with clients\' emotions.' },
  { id: 75, name: 'Providing Comfort', description: 'You find joy in comforting others, like a caregiver supporting patients through recovery.' },
  { id: 76, name: 'Mediating Conflicts', description: 'You have a knack for resolving disputes, like a negotiator facilitating agreements.' },
  { id: 77, name: 'Seeking Serenity', description: 'You pursue peaceful environments, like a mindfulness coach cultivating calm spaces.' },
  { id: 78, name: 'Promoting Acceptance', description: 'You encourage inclusivity, like a diversity officer fostering an accepting workplace.' },
  { id: 79, name: 'Maintaining Balance', description: 'You strive for equilibrium, akin to a life coach helping clients find work-life balance.' },
  { id: 80, name: 'Promoting Calm Environments', description: 'You work to reduce stress, like a wellness coordinator implementing relaxation programs.' },
  { id: 81, name: 'Spreading Peace', description: 'You are passionate about fostering harmony, akin to a diplomat negotiating peaceful resolutions.' },
];
