import { createStore } from './store.js';
import { createConnector } from './connectors.js';
import { canonicalPerson, conversationState, ownerIdFromConversationUrn, advanceStage, hydrateRelationship, renderTemplate, updateTemplateFromDraft, suggestOutcome, learningRows, OUTCOMES } from './domain.js';

const $ = selector => document.querySelector(selector), esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials = name => String(name || '?').split(/\s+/).slice(0,2).map(x => x[0] || '').join('').toUpperCase();
const store = createStore(localStorage, error => notice(error.message, true));
let connector = null, busy = false;
let lastConnectorError = null;

/**
 * Owner identity bridge. The Commercial OS runs inside the signed-in
 * /built-by-you/commercial-os page; that page hands us its Supabase access
 * token over postMessage so the server-side adapter can verify the caller.
 * No credential of any kind is stored or typed inside this app.
 */
let ownerToken = null, tokenWaiter = null;
function bindTokenBridge() {
  window.addEventListener('message', event => {
    if (event.source !== window.parent || event.data?.type !== 'commercial-os:token') return;
    ownerToken = event.data.token || null;
    tokenWaiter?.(ownerToken); tokenWaiter = null;
  });
  try { window.parent?.postMessage({ type: 'commercial-os:ready' }, '*'); } catch { /* standalone use */ }
}
function getToken() {
  if (ownerToken) return Promise.resolve(ownerToken);
  try { window.parent?.postMessage({ type: 'commercial-os:ready' }, '*'); } catch { /* standalone use */ }
  return new Promise(resolve => { tokenWaiter = resolve; setTimeout(() => { if (tokenWaiter === resolve) { tokenWaiter = null; resolve(ownerToken); } }, 2500); });
}

async function boot() { const config = await fetch('./config.json').then(r => { if (!r.ok) throw new Error('config.json could not be loaded'); return r.json(); }); store.load(config); store.commit(s => { s.settings.connectorMode = 'adapter'; s.settings.adapterUrl = config.adapter?.url || ''; s.settings.anonKey = config.adapter?.anonKey || ''; }); bindTokenBridge(); bindGlobal(); await reconnect(false); render(); }

function notice(text, error = false) { $('#notice').textContent = text; $('#notice').classList.toggle('error', error); }
function findPerson(urn) { return store.state.people.find(p => p.profileUrn === urn); }
function actionCountSince(floor) { return store.state.actions.filter(a => ['connect','message'].includes(a.type) && ['queued','sent','sending'].includes(a.status) && +new Date(a.queuedAt || a.sentAt) >= floor).length; }
// Acceptance rate is the account-health signal that matters; raw volume is not.
// Sends live in state.actions (type 'connect'), and a crawl advances an accepted
// person's stage past connection_requested, which is how acceptance is detected.
const ACCEPTED_STAGES = ['connected', 'contacted', 'replied', 'call', 'offered', 'paid', 'delivered', 'expanded'];
function acceptanceRate(minAgeDays = 7) {
  const cutoff = Date.now() - minAgeDays * 86400000;
  const mature = (store.state.actions || []).filter(a => a.type === 'connect' && a.status === 'sent' && +new Date(a.sentAt || a.queuedAt) <= cutoff);
  if (!mature.length) return null;
  const people = store.state.people || [];
  const accepted = mature.filter(a => {
    const p = people.find(x => x.profileUrn === a.profileUrn);
    return Boolean(p) && (ACCEPTED_STAGES.includes(p.commercial?.stage) || String(p.connectionDegree || '').includes('1st'));
  }).length;
  return { rate: accepted / mature.length, accepted, of: mature.length };
}
function capStatus() { const now = new Date(), day = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()), week = new Date(day), dow = week.getUTCDay(); week.setUTCDate(week.getUTCDate() - (dow === 0 ? 6 : dow - 1)); return { daily: actionCountSince(day), weekly: actionCountSince(+week), dailyCap: store.state.config.caps.perDay, weeklyCap: store.state.config.caps.perWeek }; }
function assertCap() { const c = capStatus(); if (c.daily >= c.dailyCap) throw new Error(`Daily safety cap (${c.dailyCap}) reached.`); if (c.weekly >= c.weeklyCap) throw new Error(`Weekly safety cap (${c.weeklyCap}) reached.`); }
function setPill(text, ok = false) { $('#connector-pill').textContent = text; $('#connector-pill').className = ok ? 'pill ok' : 'pill'; }
async function reconnect(show = true) {
  connector = null; const s = store.state.settings;
  try {
    connector = await createConnector(s, { getToken });
    if (connector.status) { const health = await connector.status(); if (!health.configured) { setPill('Not configured'); lastConnectorError = 'ConnectSafely is not configured on the server yet (CONNECTSAFELY_MCP_URL missing).'; notice(lastConnectorError, true); connector = null; return; } if (!health.reachable) { setPill('Unreachable'); lastConnectorError = `ConnectSafely is unreachable: ${health.error || 'no response from the upstream MCP endpoint'}`; notice(lastConnectorError, true); connector = null; return; } }
    const accounts = await connector.listAccounts({});
    const list = Array.isArray(accounts) ? accounts : accounts.accounts || accounts.people || [];
    if (!list[0]) throw new Error('No LinkedIn account returned');
    store.commit(x => { x.settings.accountId = list[0].id; x.settings.ownerName = [list[0].firstName, list[0].lastName].filter(Boolean).join(' ') || list[0].name || ''; });
    setPill(`Connected · ${store.state.settings.ownerName}`.trim(), true);
    notice('ConnectSafely connected. Searches, sync, and manually confirmed outreach are ready.');
  } catch (error) { setPill('Unreachable'); notice(error.message, true); }
}

function bindGlobal() { $('#tabs').onclick = e => { const tab = e.target.dataset.tab; if (tab) store.commit(s => s.ui.tab = tab); render(); }; document.body.addEventListener('click', handleAction); $('#restore').onchange = async e => { const file = e.target.files[0]; if (!file) return; try { store.restore(await file.text()); notice('Backup restored.'); render(); } catch (error) { notice(error.message, true); } }; $('#save-settings').onclick = e => { e.preventDefault(); try { const config = JSON.parse($('#config-editor').value); if (!Array.isArray(config.icps) || !config.templates || !config.caps) throw new Error('Config requires icps, templates and caps'); sessionStorage.setItem('connectsafely_api_key', $('#api-key').value); store.commit(s => { s.settings.connectorMode = $('#connector-mode').value; s.settings.apiBaseUrl = $('#api-base').value.trim(); s.config = config; }); $('#settings-dialog').close(); reconnect().then(render); } catch (error) { notice(`Config not saved: ${error.message}`, true); } }; store.subscribe(render); }
function openSettings() { const mode = $('#connector-mode'); const hasClaudeBridge = Boolean(globalThis.window?.claude?.use); if (hasClaudeBridge && !mode.querySelector('option[value="mcp"]')) mode.add(new Option('Claude MCP (artifact runtime)', 'mcp')); if (!hasClaudeBridge) mode.querySelector('option[value="mcp"]')?.remove(); mode.value = hasClaudeBridge ? store.state.settings.connectorMode : 'rest'; $('#api-base').value = store.state.settings.apiBaseUrl; $('#api-key').value = sessionStorage.getItem('connectsafely_api_key') || ''; $('#config-editor').value = JSON.stringify(store.state.config, null, 2); $('#settings-dialog').showModal(); }
function download(name, content) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([content], { type: 'application/json' })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
function confirmAction(title, copy, message = '') { return new Promise(resolve => { $('#confirm-title').textContent = title; $('#confirm-copy').textContent = copy; $('#confirm-message').textContent = message; $('#confirm-message').classList.toggle('hidden', !message); const d = $('#confirm-dialog'); d.showModal(); d.onclose = () => resolve(d.returnValue === 'default'); }); }

async function handleAction(e) { const button = e.target.closest('[data-action]'); if (!button || busy) return; const action = button.dataset.action, urn = decodeURIComponent(button.dataset.urn || ''); try {
  if (action === 'settings') return openSettings(); if (action === 'backup') return download(`commercial-ledger-${new Date().toISOString().slice(0,10)}.json`, store.backup());
  if (action === 'search') return runSearch(); if (action === 'crawl') return crawlConnections(); if (action === 'sync') return syncConversations(); if (action === 'connect') return connectPerson(findPerson(urn)); if (action === 'draft') return toggleDraft(urn); if (action === 'send') return sendMessage(findPerson(urn)); if (action === 'close') return store.commit(s => { const p = s.people.find(x => x.profileUrn === urn); p.relationship.closed = !p.relationship.closed; }); if (action === 'promote') return promote(findPerson(urn)); if (action === 'export-learnings') return download('learnings.json', JSON.stringify({ exportedAt: new Date().toISOString(), byTemplate: learningRows(store.state.people,'template'), byIcp: learningRows(store.state.people,'icp'), bySearchTerm: learningRows(store.state.people,'term'), byArchetype: learningRows(store.state.people,'archetype') }, null, 2));
} catch (error) { notice(error.message, true); } }

async function runSearch() { if (!connector) throw new Error('Connect the REST API in Settings first.'); const icpId = $('#find-icp').value, icp = store.state.config.icps.find(x => x.id === icpId), term = $('#find-term').value.trim(), navUrl = ($('#find-url')?.value || '').trim(); if (!term && !navUrl) throw new Error('Enter a search term, or paste a Sales Navigator search URL.'); const label = navUrl || term; busy = true; notice(`Searching LinkedIn for \u201c${label}\u201d\u2026`); try { const args = navUrl ? { accountId: store.state.settings.accountId, url: navUrl, count: 50 } : { accountId: store.state.settings.accountId, keywords: term, count: 50 }; const data = await connector.searchPeople(args); const rows = data.people || data.results || data.items || []; store.mergePeople(rows.map(p => canonicalPerson(p, icpId, label, store.state.config, store.state.settings.region))); store.commit(s => { s.ui.lastSearch = { term: label, returned: rows.length, hasMore: Boolean(data.hasMore), viaSalesNav: Boolean(navUrl), at: new Date().toISOString() }; }); notice(`Merged ${rows.length} results from ${icp.name}.`); } finally { busy = false; } }

async function crawlConnections() { if (!connector) throw new Error('Connect the REST API in Settings first.'); busy = true; let added = 0; try { while (!store.state.crawl.done && added < 60) { const data = await connector.getConnections({ accountId: store.state.settings.accountId, startIndex: store.state.crawl.offset, limit: 12 }); const rows = data.connections || data.people || data.results || []; store.mergePeople(rows.map(p => { const row = canonicalPerson(p, null, null, store.state.config, store.state.settings.region, 'connection'); advanceStage(row, 'connected'); return row; })); store.commit(s => { s.crawl.offset += rows.length; s.crawl.done = Boolean(data.endOfList); }); added += rows.length; if (!rows.length && !data.endOfList) break; } notice(`Merged ${added} connections${store.state.crawl.done ? ' · end reached' : ''}.`); } finally { busy = false; } }
async function syncConversations() { if (!connector) throw new Error('Connect the REST API in Settings first.'); busy = true; try { let cursor = null, threads = [], seen = new Set(); for (let page = 0; page < 8; page++) { const data = await connector.listConversations({ accountId: store.state.settings.accountId, count: 50, ...(cursor ? { nextCursor: cursor } : {}) }); let fresh = 0; for (const t of data.conversations || data.items || []) { const id = t.conversationUrn || t.id; if (id && !seen.has(id)) { seen.add(id); threads.push(t); fresh++; } } cursor = data.nextCursor; if (!cursor || !fresh) break; }
    for (const thread of threads.slice(0, 160)) { const urn = thread.conversationUrn || thread.id; if (!store.state.settings.ownerId) store.commit(s => s.settings.ownerId = ownerIdFromConversationUrn(urn)); const data = await connector.getConversationMessages({ accountId: store.state.settings.accountId, conversationUrn: urn }); const participant = (thread.participants || []).find(p => !String(p.profileUrn || p.participantUrn || '').includes(store.state.settings.ownerId)) || thread.participant || {}; const profileUrn = participant.profileUrn || participant.participantUrn; if (!profileUrn) continue; const conv = conversationState(data.messages || data.items || [], store.state.settings.ownerId, store.state.settings.ownerName); const existing = findPerson(profileUrn); const row = canonicalPerson({ ...(existing || participant), ...participant, profileUrn, conversationUrn: urn, conversation: conv }, existing?.icpId, existing?.source?.searchTerm, store.state.config, store.state.settings.region, 'conversation'); if (conv.direction === 'theirs') advanceStage(row, 'replied', conv.lastActivityAt); else if (conv.messageCount) advanceStage(row, 'contacted', conv.lastActivityAt); hydrateRelationship(row); const suggestion = suggestOutcome(row); if (suggestion && !row.outcomeManual) row.outcomeSuggested = suggestion; store.mergePeople([row]); }
    notice(`Synced ${threads.length} LinkedIn conversations. Suggestions need your confirmation.`); } finally { busy = false; } }
async function connectPerson(person) { assertCap(); if (!connector) throw new Error('Connector unavailable.'); if (!person || person.commercial.stage !== 'prospect') throw new Error('Only untouched prospects can receive a connection request.'); if (!await confirmAction('Send connection request?', `Connect with ${person.name} without a note? Nothing else will be sent.`)) return; const action = { id: crypto.randomUUID(), type: 'connect', profileUrn: person.profileUrn, status: 'queued', queuedAt: new Date().toISOString() }; store.commit(s => s.actions.push(action)); try { action.status = 'sending'; await connector.sendConnectionRequest({ accountId: store.state.settings.accountId, profileUrn: person.profileUrn, confirmed: true }); store.commit(() => { action.status = 'sent'; action.sentAt = new Date().toISOString(); advanceStage(person, 'connection_requested', action.sentAt); }); notice(`Connection request sent to ${person.name} — no note.`); } catch (error) { store.commit(() => { action.status = 'failed'; action.error = error.message; }); throw error; } }
function toggleDraft(urn) { const drawer = document.getElementById('d-' + encodeURIComponent(urn)); drawer.classList.toggle('hidden'); }
async function sendMessage(person) { assertCap(); if (!connector) throw new Error('Connector unavailable.'); const connected = ['connected','contacted','replied','call','offered','paid','delivered','expanded'].includes(person.commercial.stage) || person.conversation?.verified; if (!connected) throw new Error('Safety block: messages require a connection or existing verified conversation.'); const textarea = document.getElementById('m-' + encodeURIComponent(person.profileUrn)), text = textarea?.value.trim(); if (!text) throw new Error('Message is empty.'); if (!await confirmAction('Send LinkedIn message?', `This will send one message to ${person.name}. Review it carefully.`, text)) return; const action = { id: crypto.randomUUID(), type: 'message', profileUrn: person.profileUrn, status: 'queued', queuedAt: new Date().toISOString() }; store.commit(s => s.actions.push(action)); const targets = []; if (person.conversationUrn) targets.push({ conversationUrn: person.conversationUrn }); if (person.profileUrn) targets.push({ recipientProfileUrn: person.profileUrn }); if (person.profileId) targets.push({ recipientProfileId: person.profileId }); const errors = [];
  for (const target of targets) for (const messagingChannel of ['linkedin_inbox','auto']) try { action.status = 'sending'; await connector.sendMessage({ accountId: store.state.settings.accountId, messagingChannel, message: text, confirmed: true, ...target }); store.commit(() => { action.status = 'sent'; action.sentAt = new Date().toISOString(); person.sentAt = action.sentAt; person.outreach = { templateId: person.icpId || 'default', icpId: person.icpId, searchTerm: person.source?.searchTerm || null, sentAt: action.sentAt }; person.outcome = 'awaiting'; person.draft = text; advanceStage(person, 'contacted', action.sentAt); }); notice(`Message sent to ${person.name}.`); return; } catch (error) { errors.push(`${Object.keys(target)[0]}/${messagingChannel}: ${error.message}`); }
  store.commit(() => { action.status = 'failed'; action.error = errors.join(' | '); }); throw new Error(`All send attempts failed — ${errors.join(' | ')}`);
}
function promote(person) { if (person.outcome !== 'positive' || !person.draft) throw new Error('Only a positive sent thread can be promoted.'); const result = updateTemplateFromDraft(person, person.draft); store.commit(s => s.config.templates[person.icpId || 'default'] = result.template); notice(`Promoted ${person.name}’s phrasing to ${person.icpName || person.icpId}. ${result.subs.join(', ')}`); }

function render() { const tab = store.state.ui.tab; document.querySelectorAll('[data-tab]').forEach(b => b.classList.toggle('active', b.dataset.tab === tab)); const views = { find: renderFind, connections: renderConnections, relationships: renderRelationships, learnings: renderLearnings }; $('#view').innerHTML = views[tab](); bindView(); }
const KLASS_ORDER = { bullseye: 0, peer_partner: 1, operator: 2, peer: 3, not_yet: 4, cold: 5 };
const readinessRank = p => (p.excluded ? 9 : p.watch ? -1 : KLASS_ORDER[p.klass] ?? 5);
function truncationBanner() {
  const t = store.state.ui?.lastSearch;
  if (!t || t.returned > 10 || t.hasMore) return '';
  return `<div class="panel status error"><b>Search looks capped.</b> “${esc(t.term)}” returned ${t.returned} results with no further pages, and the requested count was ignored. That is LinkedIn's Commercial Use Limit, not a bad query: it truncates people-search for accounts without Sales Navigator and resets on the 1st of the month.<div class="muted">Ways through: paste a Sales Navigator search URL above · use Google X-ray (<code>site:linkedin.com/in "holonic" founder</code>) and open profiles by hand · crawl your own connections, which is unaffected · or wait for the monthly reset.</div></div>`;
}
function connectorBanner() { return connector || !lastConnectorError ? '' : `<div class="panel status error"><b>Connector offline.</b> ${esc(lastConnectorError)}<div class="muted">Scoring, drafting, backup and restore still work. Searching, crawling and sending do not.</div></div>`; }
function renderFind() { const c = capStatus(), prospects = [...store.state.people].sort((a,b)=>readinessRank(a)-readinessRank(b) || (b.score||0)-(a.score||0)); return `${connectorBanner()}<div class="panel"><div class="metric-grid"><div class="metric"><span>People</span><b>${prospects.length}</b></div><div class="metric"><span>Today</span><b>${c.daily}/${c.dailyCap}</b></div><div class="metric"><span>7 days</span><b>${c.weekly}/${c.weeklyCap}</b></div><div class="metric"><span>Connection crawl</span><b>${store.state.crawl.done?'Done':store.state.crawl.offset}</b></div>${(()=>{const a=acceptanceRate();const floor=store.state.config?.caps?.acceptRateFloor??0.35;if(!a)return '<div class="metric"><span>Accept rate</span><b>—</b></div>';const low=a.rate<floor;return `<div class="metric"><span>Accept rate${low?' ⚠':''}</span><b>${Math.round(a.rate*100)}% <span class="muted">(${a.accepted}/${a.of})</span></b>${low?`<div class="muted">below ${Math.round(floor*100)}% — cut volume, do not push</div>`:''}</div>`;})()}</div></div><div class="panel"><div class="toolbar"><select id="find-icp">${store.state.config.icps.map(i=>`<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('')}</select><input id="find-term" placeholder="LinkedIn search phrase"><button data-action="search" class="primary">Run search</button><button data-action="crawl">Crawl 60 connections</button></div><div class="toolbar"><input id="find-url" placeholder="…or paste a Sales Navigator search URL (full Boolean + filters, no commercial-use cap)" style="flex:1"><span class="muted">Sales Nav license required</span></div>${truncationBanner()}${peopleTable(prospects, 'find')}</div>`; }
function renderConnections() { const people = store.state.people.filter(p => p.commercial.stage !== 'prospect' || p.conversation?.verified).sort((a,b)=>(b.score||0)-(a.score||0)); return `<div class="panel"><div class="toolbar"><button data-action="sync" class="primary">Sync conversations</button><span class="muted">Messages are available only for connected people or verified threads. Every send requires confirmation.</span></div>${people.map(p=>personCard(p,'connections')).join('') || '<p>No connections yet. Crawl them from Find.</p>'}</div>`; }
function renderRelationships() { const people = store.state.people.map(hydrateRelationship).filter(p=>!p.relationship.closed).sort((a,b)=>(b.followupScore||0)-(a.followupScore||0)); return `<div class="panel"><div class="toolbar"><button data-action="sync" class="primary">Sync & triage</button><span class="muted">Booking and close signals are deterministic; booked calls snooze 14 days unless a fresh question follows.</span></div>${people.map(p=>personCard(p,'relationships')).join('') || '<p>No relationships yet.</p>'}</div>`; }
function renderLearnings() { const mode = store.state.ui.learningMode || 'template', rows = learningRows(store.state.people, mode); return `<div class="panel"><div class="toolbar"><select id="learning-mode"><option value="template" ${mode==='template'?'selected':''}>By template</option><option value="icp" ${mode==='icp'?'selected':''}>By ICP</option><option value="term" ${mode==='term'?'selected':''}>By search term</option><option value="archetype" ${mode==='archetype'?'selected':''}>By archetype</option></select><button data-action="export-learnings">Export learnings.json</button></div><div class="table-wrap"><table><thead><tr><th>${mode}</th><th>Sent</th><th>Replied</th><th>Positive</th><th>Reply rate</th><th>Positive rate</th><th>Signal</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${esc(r.key)}</td><td>${r.sent}</td><td>${r.replied}</td><td>${r.positive}</td><td>${(r.replyRate*100).toFixed(1)}%</td><td>${(r.positiveRate*100).toFixed(1)}%</td><td>${rows.length>1?(i===0?'Top':i===rows.length-1?'Bottom':'—'):'—'}</td></tr>`).join('')}</tbody></table></div></div>`; }
function peopleTable(people) { return `<div class="table-wrap"><table><thead><tr><th>Person</th><th>Fit</th><th>Source</th><th>Stage</th><th>Action</th></tr></thead><tbody>${people.map(p=>`<tr><td><a href="${esc(p.profileUrl||'#')}" target="_blank" rel="noopener">${esc(p.name)}</a><div class="muted">${esc(p.headline)}</div></td><td><span class="score">${p.score||0}</span>${p.streamRole?`<span class="tag">${esc(p.streamRole)}</span>`:''}${p.klass?`<span class="tag">${esc(p.klass)}</span>`:''}${p.watch?`<span class="tag">👁 watch</span>`:''}${p.mf?.tier?`<span class="tag">MF${p.mf.tier}</span>`:''}<div class="muted">${esc(p.reason||'')}</div></td><td>${esc(p.source?.searchTerm||p.source?.mechanism||'')}</td><td>${esc(p.commercial.stage)}</td><td>${p.excluded?'excluded':p.watch?`<a href="${esc(p.profileUrl||'#')}" target="_blank" rel="noopener">Open profile</a>`:p.klass==='not_yet'?'not yet':p.commercial.stage==='prospect'?`<button data-action="connect" data-urn="${encodeURIComponent(p.profileUrn)}">Connect · no note</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`; }
function archetypeControl(p, urn) {
  const list = store.state.config.archetypes?.items || [];
  if (!list.length) return '';
  const cur = p.archetype || {};
  const sent = Boolean(p.sentAt);
  return `<label class="muted" title="${sent ? 'Labelled before contact' : 'Call it before you write'}">Archetype
    <select data-arch="${urn}" ${sent && cur.id ? 'disabled' : ''}>
      <option value="">unlabelled</option>
      ${list.map(a=>`<option value="${esc(a.id)}" ${a.id===cur.id?'selected':''} title="${esc(a.one_line)}">${esc(a.name)}</option>`).join('')}
    </select>
    <input data-archmatch="${urn}" type="number" min="1" max="10" step="1" placeholder="1-10" value="${cur.match ?? ''}" style="width:56px" title="How well they match that archetype">
  </label>`;
}
function pickTemplate(p) { const t = store.state.config.templates; if (p.klass === 'not_yet') return t.not_yet; return t[`${p.icpId}__${p.register}`] || t[p.icpId] || t.default; }
function personCard(p, mode) { const template = renderTemplate(pickTemplate(p), p), urn = encodeURIComponent(p.profileUrn), suggestion = p.outcomeSuggested && !p.outcomeManual ? ` · suggested: ${p.outcomeSuggested}` : ''; return `<article class="person"><div class="avatar">${initials(p.name)}</div><div><a href="${esc(p.profileUrl||'#')}" target="_blank" rel="noopener"><b>${esc(p.name)}</b></a><div class="muted">${esc(p.headline)}</div><span class="tag">${esc(p.commercial.stage)}</span></div><div><b>${mode==='relationships'?esc((p.triage?.state||'active').replaceAll('_',' ')):esc(p.conversation?.direction||'unverified')}</b><div class="muted">${mode==='relationships'?esc(p.triage?.reason||''):esc(p.conversation?.lastText||'No messages loaded')}</div>${p.outreach?`<label class="muted">Outcome${suggestion}<select data-outcome="${urn}">${OUTCOMES.map(x=>`<option ${x===(p.outcome||'awaiting')?'selected':''}>${x}</option>`).join('')}</select></label>`:''}</div><div class="actions">${archetypeControl(p,urn)}<button data-action="draft" data-urn="${urn}">Draft / context</button>${mode==='relationships'?`<button data-action="close" data-urn="${urn}">Close</button>`:''}${p.outcome==='positive'?`<button data-action="promote" data-urn="${urn}">Promote winner</button>`:''}</div><div id="d-${urn}" class="drawer hidden"><textarea id="m-${urn}" rows="9">${esc(p.draft||template)}</textarea><div class="actions"><button class="primary" data-action="send" data-urn="${urn}">Review & send</button><span class="muted">LinkedIn inbox first; fallback attempts are reported in full.</span></div></div></article>`; }
function bindView() { const icp = $('#find-icp'), term = $('#find-term'); if (icp && term) { const setTerms = () => { const item=store.state.config.icps.find(x=>x.id===icp.value); term.value=item?.terms?.[0]||''; }; icp.onchange=setTerms; setTerms(); } $('#learning-mode')?.addEventListener('change', e => { store.commit(s => s.ui.learningMode=e.target.value); }); document.querySelectorAll('[data-arch]').forEach(el => el.onchange = () => store.commit(s => {
    const p = s.people.find(x => x.profileUrn === decodeURIComponent(el.dataset.arch));
    p.archetype = el.value ? { ...(p.archetype||{}), id: el.value, calledAt: new Date().toISOString(), beforeContact: !p.sentAt } : null;
  }));
  document.querySelectorAll('[data-archmatch]').forEach(el => el.onchange = () => store.commit(s => {
    const p = s.people.find(x => x.profileUrn === decodeURIComponent(el.dataset.archmatch));
    const v = Math.max(1, Math.min(10, Number(el.value) || 0));
    if (p.archetype) p.archetype.match = v || null;
  }));
  document.querySelectorAll('[data-outcome]').forEach(el => el.onchange = () => store.commit(s => { const p=s.people.find(x=>x.profileUrn===decodeURIComponent(el.dataset.outcome)); p.outcome=el.value; p.outcomeManual=true; p.outcomeSuggested=null; })); }

boot().catch(error => notice(error.message, true));
