// Ported from the three tested core.mjs references so this folder deploys standalone.
export const STAGES = ['prospect','connection_requested','connected','contacted','replied','call','offered','paid','delivered','expanded'];
export function emptyCommercial(){return{stage:'prospect',connectionRequestedAt:null,connectedAt:null,contactedAt:null,repliedAt:null,callAt:null,offerAt:null,paymentAt:null,deliveredAt:null,expansionAt:null,amountUsd:0,offerType:null}}
export function normalizeRecord(raw){const profileUrn=raw.profileUrn||raw.linkedin?.profileUrn||'',email=String(raw.email||raw.primaryEmail||'').toLowerCase(),identity=raw.id||raw.key||(profileUrn?'linkedin:'+profileUrn:email?'email:'+email:'');if(!identity)throw new Error('Ledger record has no stable identity');return{...raw,id:identity,profileUrn,email,channels:[...new Set([...(raw.channels||[]),profileUrn&&'linkedin',email&&'email'].filter(Boolean))],source:{channel:raw.source?.channel||(profileUrn?'linkedin':'email'),mechanism:raw.source?.mechanism||'unknown',searchTerm:raw.source?.searchTerm||null,foundByIcpId:raw.source?.foundByIcpId||raw.icpId||null,capturedAt:raw.source?.capturedAt||null},commercial:{...emptyCommercial(),...(raw.commercial||{})},relationship:raw.relationship||raw.state||{},conversation:raw.conversation||{},lineage:[...new Set([...(raw.lineage||[]),raw.source?.mechanism].filter(Boolean))]}}
export function mergeLedgerRecords(...lists){const map=new Map();for(const raw of lists.flat()){const r=normalizeRecord(raw),key=r.profileUrn?'li:'+r.profileUrn:r.email?'em:'+r.email:r.id,old=map.get(key);if(!old){map.set(key,r);continue}const stage=STAGES.indexOf(r.commercial.stage)>STAGES.indexOf(old.commercial.stage)?r.commercial.stage:old.commercial.stage;map.set(key,{...old,...r,source:old.source.mechanism!=='unknown'?old.source:r.source,channels:[...new Set([...old.channels,...r.channels])],commercial:{...old.commercial,...r.commercial,stage},relationship:{...old.relationship,...r.relationship},lineage:[...new Set([...old.lineage,...r.lineage])]})}return[...map.values()]}
export function profileIdFromUrl(url=''){return String(url).match(/linkedin\.com\/in\/([^/?#]+)/i)?.[1]||''}
export function renderTemplate(template,person){const company=person.company||'';return String(template).replace(/\[\[company:\s*([\s\S]*?)\]\]/g,company?(_,text)=>text.replaceAll('{company}',company):'').replaceAll('{first}',person.firstName||person.name?.split(' ')[0]||'there').replaceAll('{name}',person.name||'').replaceAll('{company}',company)}
export function updateTemplateFromDraft(person,draft){let template=String(draft);const subs=[],replace=(value,token)=>{if(value&&value.length>1){const re=new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g');if(re.test(template)){template=template.replace(re,token);subs.push(value+' → '+token)}}};replace((person.company||'').trim(),'{company}');replace((person.name||'').trim(),'{name}');replace((person.firstName||person.name?.split(' ')[0]||'').trim(),'{first}');return{template,subs}}
const WINDOWS={lead:4,client:7,investor:6,personal:14,unlabeled:5,promotional:Infinity};
function newer(a,b){if(!a)return b;if(!b)return a;return new Date(b.ts||0)>=new Date(a.ts||0)?b:a}
function latestActivity(contact){return newer(contact.emailActivity,contact.linkedinActivity)||{ts:null,lastMine:false,thread:[]}}
function structuralStatus(contact,now=Date.now()){const activity=latestActivity(contact);if(!activity.ts)return{status:'ok',days:null,due:false};const days=Math.max(0,Math.floor((now-new Date(activity.ts).getTime())/86400000)),category=contact.state?.category||'unlabeled',window=activity.lastMine?(WINDOWS[category]??WINDOWS.unlabeled):2;return{status:activity.lastMine?'wait':'turn',days,due:days>=window}}
const bookingRe=/\b(booked|calendly|cal\.com|calendar invite|invite sent|scheduled|confirmed for|looking forward to (our|the) (call|chat|meeting)|see you (then|on|tuesday|wednesday|thursday|friday|monday))\b/i,closedRe=/\b(not (a fit|interested|right now)|pass for now|no thanks|will not proceed|closed the loop)\b/i;
export function deterministicTriage(contact){const activity=latestActivity(contact),messages=activity.thread||[],joined=messages.slice(-8).map(m=>m.text||m.body||m.content||'').join('\n');if(closedRe.test(joined))return{state:'closed',reason:'Explicit close language'};if(bookingRe.test(joined)){const marks=messages.map(m=>bookingRe.test(m.text||m.body||m.content||'')),lastBookingIndex=marks.lastIndexOf(true),freshQuestion=messages.slice(lastBookingIndex+1).some(m=>m.mine&&/\?/.test(m.text||m.body||m.content||''));if(!freshQuestion)return{state:'meeting_scheduled',reason:'Deterministic booking signal'}}const structural=structuralStatus(contact);if(!structural.due)return{state:activity.lastMine?'awaiting_them':'active',reason:'Inside follow-up window'};return{state:'needs_followup',reason:structural.status==='turn'?'Their reply is waiting':'Follow-up window elapsed'}}
export function applyBookedSnooze(contact,triage,now=Date.now()){if(triage.state!=='meeting_scheduled'||contact.state?.closed)return contact;const current=new Date(contact.state?.snoozeUntil||0).getTime(),proposed=now+14*86400000;if(current>=proposed)return contact;return{...contact,state:{...contact.state,snoozeUntil:new Date(proposed).toISOString(),autoSnoozed:true,autoSnoozeTs:latestActivity(contact).ts}}}
export function followupScore(contact,now=Date.now()){const s=structuralStatus(contact,now),triage=contact.triage||deterministicTriage(contact);if(contact.state?.closed||triage.state==='closed'||triage.state==='meeting_scheduled')return-10000;const category={investor:35,lead:30,client:25,personal:5,promotional:-100,unlabeled:10}[contact.state?.category||'unlabeled'],back=contact.state?.snoozeUntil&&new Date(contact.state.snoozeUntil)<=now?50:0;return(s.days||0)*3+(s.status==='turn'?35:0)+(triage.state==='needs_followup'?60:0)+category+back}
