/**
 * PublicLandingPage — world-readable Landing Page served at /ubl/:slugWithVersion.
 *
 * Fetches the row from unique_business_dossiers by slug and renders the
 * landing_page artifact content as a marketing surface.
 *
 * Day 52 (Sasha 2026-04-26) — defensive rendering:
 * The /ubb landing_page artifact is generated by an LLM and the prompt asks
 * for a strict schema (headline / subheadline / pain / promise / proof[] /
 * value_ladder / cta), but the model occasionally returns a different shape
 * (price/outcome, _energies/_distillation from the synthesis protocol, plain
 * strings for fields expected as arrays, etc.). Earlier this surfaced as
 * "Something went wrong / Refresh" on the public URL — a thrown exception
 * caught by the app-level ErrorBoundary because `proof_section.map()` was
 * called on a string.
 *
 * The page now:
 *   • coerces every field to its expected primitive shape with `asString` /
 *     `asArray` / `asCta` helpers so no field can throw on render
 *   • after rendering known fields, shows ANY remaining content keys as a
 *     "Below the fold" fallback so the published artifact never appears
 *     blank when the AI returns an unfamiliar shape
 *   • internal-protocol tracer fields (_energies, _distillation) are
 *     stripped before display so they don't leak to public viewers
 */

import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";

type CtaShape = { text?: string; mechanism?: string; url?: string };

type DossierRow = {
  id: string;
  slug: string;
  title: string;
  artifact_snapshot: Record<string, { version: number; content: unknown; specificity_score: number }>;
  landing_page_version: string | null;
  published_at: string;
  is_live: boolean;
};

// Coerce anything to a clean string. Objects/arrays JSON-stringify so they
// at least render *something*, but won't throw downstream.
const asString = (v: unknown): string => {
  if (v == null) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  try { return JSON.stringify(v); } catch { return ""; }
};

// Coerce to an array of clean strings. Strings get split by sentence-ish
// breaks if they look list-y; otherwise treated as single item. Object items
// get stringified.
const asArray = (v: unknown): string[] => {
  if (v == null || v === "") return [];
  if (Array.isArray(v)) return v.map(asString).filter(Boolean);
  if (typeof v === "string") return [v];
  if (typeof v === "object") return [asString(v)];
  return [String(v)];
};

const asCta = (v: unknown): CtaShape | null => {
  if (!v) return null;
  if (typeof v === "string") return { text: v };
  if (typeof v === "object") return v as CtaShape;
  return null;
};

// Internal tracer fields that the synthesis protocol writes for its own
// audit trail — these should never reach a public viewer.
const HIDDEN_KEYS = new Set([
  "_energies", "_distillation",
  "meta", // contains slug/og_image — internal plumbing
]);

// Known content keys the page renders as first-class sections.
const KNOWN_KEYS = new Set([
  "headline", "subheadline", "pain_section", "promise_section",
  "proof_section", "value_ladder_section", "cta",
]);

const formatLabel = (key: string): string =>
  key.replace(/[_-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

export default function PublicLandingPage() {
  const { slugWithVersion } = useParams<{ slugWithVersion: string }>();
  const [dossier, setDossier] = useState<DossierRow | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    (async () => {
      if (!slugWithVersion) return;
      setLoading(true);
      try {
        const { data, error } = await (supabase as any)
          .from("unique_business_dossiers")
          .select("*")
          .eq("slug", slugWithVersion)
          .eq("is_live", true)
          .maybeSingle();
        if (error || !data) {
          setNotFound(true);
        } else {
          setDossier(data as DossierRow);
        }
      } catch (e) {
        console.error("[PublicLandingPage] load error:", e);
        setNotFound(true);
      } finally {
        setLoading(false);
      }
    })();
  }, [slugWithVersion]);

  if (loading) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-sm text-white/60">Loading…</div>
      </div>
    );
  }

  if (notFound || !dossier) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-xl font-medium">Page not found</h1>
          <p className="mt-2 text-sm text-white/60">
            This landing page may have been unpublished or never existed.
          </p>
        </div>
      </div>
    );
  }

  const landingEntry = dossier.artifact_snapshot?.landing_page;
  const rawContent = (landingEntry?.content || {}) as Record<string, unknown>;

  const headline = asString(rawContent.headline);
  const subheadline = asString(rawContent.subheadline);
  const painSection = asString(rawContent.pain_section);
  const promiseSection = asString(rawContent.promise_section);
  const proofSection = asArray(rawContent.proof_section);
  const valueLadder = asString(rawContent.value_ladder_section);
  const cta = asCta(rawContent.cta);

  // Anything else the AI generated (e.g. price, outcome, deliverable, ...)
  // — render as labeled blocks below the known sections so the page is
  // never blank just because the schema drifted.
  const extraKeys = Object.keys(rawContent).filter(
    (k) => !HIDDEN_KEYS.has(k) && !KNOWN_KEYS.has(k)
  );

  // If literally NO usable content was extracted, show a friendly state
  // instead of a blank page.
  const hasAnyContent =
    headline || subheadline || painSection || promiseSection ||
    proofSection.length > 0 || valueLadder || cta || extraKeys.length > 0;

  return (
    <div className="min-h-screen bg-gradient-to-b from-zinc-950 to-black text-white">
      <main className="mx-auto max-w-3xl px-6 py-20 space-y-12">
        {!hasAnyContent && (
          <section className="text-center space-y-3 py-20">
            <h1 className="text-2xl font-medium">{dossier.title || "Landing Page"}</h1>
            <p className="text-sm text-white/60">
              This page was published but doesn't have rendered content yet.
            </p>
          </section>
        )}

        {/* Hero */}
        {headline && (
          <section className="space-y-4 text-center">
            <h1 className="text-4xl sm:text-5xl font-semibold tracking-tight leading-tight">
              {headline}
            </h1>
            {subheadline && (
              <p className="mx-auto max-w-2xl text-lg text-white/70 leading-relaxed">
                {subheadline}
              </p>
            )}
          </section>
        )}

        {/* Pain */}
        {painSection && (
          <section className="rounded-xl border border-white/10 bg-white/5 p-6 backdrop-blur">
            <div className="whitespace-pre-wrap text-base leading-relaxed text-white/85">
              {painSection}
            </div>
          </section>
        )}

        {/* Promise */}
        {promiseSection && (
          <section className="space-y-2">
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-white/50">
              What this makes possible
            </h2>
            <div className="whitespace-pre-wrap text-lg leading-relaxed">
              {promiseSection}
            </div>
          </section>
        )}

        {/* Proof */}
        {proofSection.length > 0 && (
          <section className="space-y-3">
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-white/50">
              Proof
            </h2>
            <div className="space-y-3">
              {proofSection.map((p, i) => (
                <blockquote
                  key={i}
                  className="rounded-lg border-l-2 border-white/30 bg-white/5 px-5 py-3 text-base italic text-white/85"
                >
                  {p}
                </blockquote>
              ))}
            </div>
          </section>
        )}

        {/* Value ladder */}
        {valueLadder && (
          <section className="space-y-2">
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-white/50">
              Options
            </h2>
            <div className="whitespace-pre-wrap text-base leading-relaxed text-white/85">
              {valueLadder}
            </div>
          </section>
        )}

        {/* CTA */}
        {cta && (cta.text || cta.url) && (
          <section className="pt-4 text-center">
            {cta.url ? (
              <a
                href={cta.url}
                className="inline-flex items-center gap-2 rounded-full bg-white px-7 py-3 text-base font-medium text-black transition-transform hover:scale-[1.02]"
              >
                {cta.text || "Get started"}
              </a>
            ) : (
              <div className="rounded-full bg-white/10 px-7 py-3 text-base font-medium inline-block">
                {cta.text || "Get started"}
              </div>
            )}
          </section>
        )}

        {/* Extra fields the AI generated outside the known schema
            — rendered as labeled blocks so the page never appears blank
            when the model wandered. */}
        {extraKeys.length > 0 && (
          <section className="space-y-4 pt-4 border-t border-white/10">
            {extraKeys.map((key) => {
              const value = rawContent[key];
              const valueStr = asString(value);
              if (!valueStr) return null;
              return (
                <div key={key} className="space-y-1">
                  <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-white/50">
                    {formatLabel(key)}
                  </h2>
                  <div className="whitespace-pre-wrap text-base leading-relaxed text-white/85">
                    {valueStr}
                  </div>
                </div>
              );
            })}
          </section>
        )}

        {/* Footer */}
        <footer className="pt-12 border-t border-white/10 text-xs text-white/40 text-center">
          Published {new Date(dossier.published_at).toLocaleDateString()} ·{" "}
          {dossier.landing_page_version || "v?"}
        </footer>
      </main>
    </div>
  );
}
