/**
 * PublicLandingPage — world-readable Landing Page served at /ubl/:slugWithVersion.
 *
 * Fetches the row from unique_business_dossiers by slug and renders the
 * landing_page artifact content as a marketing surface.
 *
 * Day 52 (Sasha 2026-04-26) — defensive rendering:
 * The /ubb landing_page artifact is generated by an LLM and the prompt
 * asks for a strict schema (headline / subheadline / pain / promise /
 * proof[] / value_ladder / cta), but the model occasionally returns a
 * different shape. The page coerces every field with `asString` /
 * `asArray` / `asCta` helpers so no field can throw on render. After
 * rendering known fields, ANY remaining content keys render as a
 * "Below the fold" fallback so the published artifact never appears
 * blank when the AI returns an unfamiliar shape. Internal-protocol
 * tracer fields (_energies, _distillation) are stripped before display.
 *
 * Day 53 (Sasha 2026-04-27): full editorial re-skin to match the
 * landing/playbook brand register. Was: dark zinc-on-black SaaS
 * aesthetic. Now: cream wash + Cormorant Garamond cinematic headline
 * + Source Serif 4 italic body + gold-haloed CTA pill, matching the
 * platform's `/` landing. The founder's published landing inherits
 * the brand's editorial gravitas — strangers landing on /ubl/{slug}
 * see a serious brand, not a generic dark template.
 */

import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";

type CtaShape = { text?: string; mechanism?: string; url?: string };

type DossierRow = {
  id: string;
  slug: string;
  title: string;
  artifact_snapshot: Record<string, { version: number; content: unknown; specificity_score: number }>;
  landing_page_version: string | null;
  published_at: string;
  is_live: boolean;
};

const asString = (v: unknown): string => {
  if (v == null) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  try { return JSON.stringify(v); } catch { return ""; }
};

const asArray = (v: unknown): string[] => {
  if (v == null || v === "") return [];
  if (Array.isArray(v)) return v.map(asString).filter(Boolean);
  if (typeof v === "string") return [v];
  if (typeof v === "object") return [asString(v)];
  return [String(v)];
};

const asCta = (v: unknown): CtaShape | null => {
  if (!v) return null;
  if (typeof v === "string") return { text: v };
  if (typeof v === "object") return v as CtaShape;
  return null;
};

const HIDDEN_KEYS = new Set([
  "_energies", "_distillation",
  "meta",
]);

const KNOWN_KEYS = new Set([
  "headline", "subheadline", "pain_section", "promise_section",
  "proof_section", "value_ladder_section", "cta",
]);

const formatLabel = (key: string): string =>
  key.replace(/[_-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

// Cream wash matches the platform `/` landing — gold sun-glow at top right.
const WASH_BG =
  "radial-gradient(ellipse 95% 105% at 95% 5%, rgba(255, 200, 130, 0.55) 0%, rgba(255, 218, 170, 0.45) 18%, rgba(252, 232, 200, 0.75) 38%, rgba(248, 240, 220, 0.92) 65%, rgba(245, 242, 235, 0.98) 88%)";

export default function PublicLandingPage() {
  const { slugWithVersion } = useParams<{ slugWithVersion: string }>();
  const [dossier, setDossier] = useState<DossierRow | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    (async () => {
      if (!slugWithVersion) return;
      setLoading(true);
      try {
        const { data, error } = await (supabase as any)
          .from("unique_business_dossiers")
          .select("*")
          .eq("slug", slugWithVersion)
          .eq("is_live", true)
          .maybeSingle();
        if (error || !data) {
          setNotFound(true);
        } else {
          setDossier(data as DossierRow);
        }
      } catch (e) {
        console.error("[PublicLandingPage] load error:", e);
        setNotFound(true);
      } finally {
        setLoading(false);
      }
    })();
  }, [slugWithVersion]);

  if (loading) {
    return (
      <div
        className="flex min-h-screen items-center justify-center"
        style={{ background: WASH_BG }}
      >
        <div
          style={{
            fontFamily: "'Source Serif 4', serif",
            fontStyle: "italic",
            fontSize: "15px",
            color: "rgba(11, 42, 90, 0.55)",
          }}
        >
          Loading…
        </div>
      </div>
    );
  }

  if (notFound || !dossier) {
    return (
      <div
        className="flex min-h-screen items-center justify-center"
        style={{ background: WASH_BG }}
      >
        <div className="text-center">
          <h1
            style={{
              fontFamily: "'Cormorant Garamond', serif",
              fontWeight: 600,
              fontSize: "28px",
              color: "#0b2a5a",
            }}
          >
            Page not found
          </h1>
          <p
            className="mt-2"
            style={{
              fontFamily: "'Source Serif 4', serif",
              fontStyle: "italic",
              fontSize: "14px",
              color: "rgba(11, 42, 90, 0.62)",
            }}
          >
            This landing page may have been unpublished or never existed.
          </p>
        </div>
      </div>
    );
  }

  const landingEntry = dossier.artifact_snapshot?.landing_page;
  const rawContent = (landingEntry?.content || {}) as Record<string, unknown>;

  const headline = asString(rawContent.headline);
  const subheadline = asString(rawContent.subheadline);
  const painSection = asString(rawContent.pain_section);
  const promiseSection = asString(rawContent.promise_section);
  const proofSection = asArray(rawContent.proof_section);
  const valueLadder = asString(rawContent.value_ladder_section);
  const cta = asCta(rawContent.cta);

  const extraKeys = Object.keys(rawContent).filter(
    (k) => !HIDDEN_KEYS.has(k) && !KNOWN_KEYS.has(k)
  );

  const hasAnyContent =
    headline || subheadline || painSection || promiseSection ||
    proofSection.length > 0 || valueLadder || cta || extraKeys.length > 0;

  return (
    <div className="min-h-screen" style={{ background: WASH_BG }}>
      <main className="mx-auto max-w-3xl space-y-14 px-5 py-20">
        {!hasAnyContent && (
          <section className="space-y-3 py-20 text-center">
            <h1
              style={{
                fontFamily: "'Cormorant Garamond', serif",
                fontWeight: 600,
                fontSize: "28px",
                color: "#0b2a5a",
              }}
            >
              {dossier.title || "Landing Page"}
            </h1>
            <p
              style={{
                fontFamily: "'Source Serif 4', serif",
                fontStyle: "italic",
                fontSize: "14px",
                color: "rgba(11, 42, 90, 0.62)",
              }}
            >
              This page was published but doesn't have rendered content yet.
            </p>
          </section>
        )}

        {/* ═══ Hero ═══ Cinematic Cormorant headline + italic subhead */}
        {headline && (
          <section className="space-y-5 text-center">
            <h1
              className="leading-[1.05]"
              style={{
                fontFamily: "'Cormorant Garamond', serif",
                fontWeight: 600,
                fontSize: "clamp(40px, 6vw, 64px)",
                letterSpacing: "-0.012em",
                color: "#0b2a5a",
                textShadow: "0 1px 2px rgba(255,255,255,0.7), 0 0 22px rgba(255,255,255,0.55)",
              }}
            >
              {headline}
            </h1>
            {subheadline && (
              <p
                className="mx-auto max-w-2xl"
                style={{
                  fontFamily: "'Source Serif 4', serif",
                  fontStyle: "italic",
                  fontSize: "clamp(16px, 1.6vw, 19px)",
                  lineHeight: 1.55,
                  color: "rgba(11, 42, 90, 0.85)",
                }}
              >
                {subheadline}
              </p>
            )}
            {/* Ornament rule */}
            <div className="flex items-center justify-center gap-3 pt-3">
              <div
                className="h-px w-16"
                style={{
                  background:
                    "linear-gradient(90deg, rgba(212, 175, 55, 0) 0%, rgba(212, 175, 55, 0.45) 100%)",
                }}
              />
              <span
                aria-hidden="true"
                style={{
                  color: "#b8860b",
                  textShadow: "0 0 12px rgba(240,194,127,0.7), 0 0 3px rgba(240,194,127,0.9)",
                  fontSize: "16px",
                }}
              >
                ✦
              </span>
              <div
                className="h-px w-16"
                style={{
                  background:
                    "linear-gradient(90deg, rgba(212, 175, 55, 0.45) 0%, rgba(212, 175, 55, 0) 100%)",
                }}
              />
            </div>
          </section>
        )}

        {/* ═══ Pain ═══ Editorial card */}
        {painSection && (
          <section
            className="rounded-2xl px-6 py-6"
            style={{
              background: "rgba(255, 255, 255, 0.55)",
              border: "0.5px solid rgba(26, 30, 58, 0.08)",
              boxShadow:
                "0 4px 16px -8px rgba(10, 22, 40, 0.10), 0 16px 40px -20px rgba(10, 22, 40, 0.15)",
            }}
          >
            <div
              className="whitespace-pre-wrap"
              style={{
                fontFamily: "'Source Serif 4', serif",
                fontSize: "16.5px",
                lineHeight: 1.62,
                color: "rgba(11, 42, 90, 0.88)",
              }}
            >
              {painSection}
            </div>
          </section>
        )}

        {/* ═══ Promise ═══ */}
        {promiseSection && (
          <section className="space-y-3">
            <SectionLabel>What this makes possible</SectionLabel>
            <div
              className="whitespace-pre-wrap"
              style={{
                fontFamily: "'Cormorant Garamond', serif",
                fontWeight: 500,
                fontSize: "clamp(20px, 2.4vw, 26px)",
                lineHeight: 1.4,
                letterSpacing: "-0.005em",
                color: "#0b2a5a",
                textShadow: "0 1px 2px rgba(255,255,255,0.6)",
              }}
            >
              {promiseSection}
            </div>
          </section>
        )}

        {/* ═══ Proof ═══ Pull quotes */}
        {proofSection.length > 0 && (
          <section className="space-y-4">
            <SectionLabel>Proof</SectionLabel>
            <div className="space-y-4">
              {proofSection.map((p, i) => (
                <blockquote
                  key={i}
                  className="rounded-xl px-5 py-4"
                  style={{
                    background: "rgba(255, 255, 255, 0.45)",
                    borderLeft: "2px solid #b8860b",
                    boxShadow: "0 0 16px -8px rgba(212, 175, 55, 0.30)",
                  }}
                >
                  <p
                    className="italic"
                    style={{
                      fontFamily: "'Source Serif 4', serif",
                      fontSize: "16px",
                      lineHeight: 1.55,
                      color: "rgba(11, 42, 90, 0.88)",
                    }}
                  >
                    {p}
                  </p>
                </blockquote>
              ))}
            </div>
          </section>
        )}

        {/* ═══ Value ladder ═══ */}
        {valueLadder && (
          <section className="space-y-3">
            <SectionLabel>Options</SectionLabel>
            <div
              className="whitespace-pre-wrap"
              style={{
                fontFamily: "'Source Serif 4', serif",
                fontSize: "16px",
                lineHeight: 1.6,
                color: "rgba(11, 42, 90, 0.85)",
              }}
            >
              {valueLadder}
            </div>
          </section>
        )}

        {/* ═══ CTA ═══ Ceremonial pill matching landing CTAs */}
        {cta && (cta.text || cta.url) && (
          <section className="pt-4 text-center">
            {cta.url ? (
              <a
                href={cta.url}
                className="group relative inline-flex items-center gap-2.5 rounded-full px-7 py-3.5 transition-all duration-300 hover:translate-y-[-1px]"
                style={{
                  background:
                    "linear-gradient(135deg, rgba(10,22,40,0.82) 0%, rgba(18,28,56,0.72) 50%, rgba(10,22,40,0.82) 100%)",
                  color: "rgba(245, 245, 250, 0.98)",
                  border: "0.5px solid rgba(255, 255, 255, 0.14)",
                  boxShadow:
                    "0 0 0 1px rgba(212, 175, 55, 0.32), 0 0 22px -4px rgba(240, 194, 127, 0.50), 0 0 48px -10px rgba(212, 175, 55, 0.32), 0 12px 32px -10px rgba(10, 22, 40, 0.55)",
                  backdropFilter: "blur(14px) saturate(160%)",
                  WebkitBackdropFilter: "blur(14px) saturate(160%)",
                }}
              >
                <span
                  aria-hidden="true"
                  className="transition-transform duration-300 group-hover:scale-110"
                  style={{
                    color: "rgba(244, 212, 114, 0.98)",
                    textShadow: "0 0 12px rgba(244,212,114,0.8), 0 0 4px rgba(212,175,55,0.9)",
                    fontSize: "17px",
                  }}
                >
                  ✦
                </span>
                <span
                  style={{
                    fontFamily: "'Cormorant Garamond', serif",
                    fontWeight: 600,
                    letterSpacing: "0.14em",
                    textTransform: "uppercase",
                    fontSize: "14px",
                    textShadow: "0 0 16px rgba(240,194,127,0.32), 0 1px 2px rgba(0,0,0,0.4)",
                  }}
                >
                  {cta.text || "Get started"}
                </span>
                <span
                  aria-hidden="true"
                  className="transition-transform duration-300 group-hover:translate-x-0.5"
                  style={{ color: "rgba(244, 212, 114, 0.98)" }}
                >
                  →
                </span>
              </a>
            ) : (
              <div
                className="inline-flex items-center gap-2 rounded-full px-7 py-3"
                style={{
                  background: "rgba(255, 255, 255, 0.55)",
                  border: "0.5px solid rgba(212, 175, 55, 0.55)",
                  boxShadow: "0 0 14px -4px rgba(212, 175, 55, 0.32)",
                  fontFamily: "'Cormorant Garamond', serif",
                  fontWeight: 600,
                  letterSpacing: "0.14em",
                  textTransform: "uppercase",
                  fontSize: "13px",
                  color: "#0b2a5a",
                }}
              >
                {cta.text || "Get started"}
              </div>
            )}
          </section>
        )}

        {/* ═══ Extra fields (schema drift fallback) ═══ */}
        {extraKeys.length > 0 && (
          <section
            className="space-y-5 pt-6"
            style={{
              borderTop: "0.5px solid rgba(26, 30, 58, 0.10)",
            }}
          >
            {extraKeys.map((key) => {
              const value = rawContent[key];
              const valueStr = asString(value);
              if (!valueStr) return null;
              return (
                <div key={key} className="space-y-2">
                  <SectionLabel>{formatLabel(key)}</SectionLabel>
                  <div
                    className="whitespace-pre-wrap"
                    style={{
                      fontFamily: "'Source Serif 4', serif",
                      fontSize: "15.5px",
                      lineHeight: 1.6,
                      color: "rgba(11, 42, 90, 0.85)",
                    }}
                  >
                    {valueStr}
                  </div>
                </div>
              );
            })}
          </section>
        )}

        {/* ═══ Footer ═══ */}
        <footer
          className="pt-10 text-center"
          style={{ borderTop: "0.5px solid rgba(26, 30, 58, 0.10)" }}
        >
          <div
            style={{
              fontFamily: "'DM Sans', system-ui, sans-serif",
              fontSize: "10.5px",
              letterSpacing: "0.18em",
              textTransform: "uppercase",
              color: "rgba(11, 42, 90, 0.45)",
              fontVariantNumeric: "tabular-nums lining-nums",
            }}
          >
            Published {new Date(dossier.published_at).toLocaleDateString()} ·{" "}
            {dossier.landing_page_version || "v?"}
          </div>
          <div
            className="mt-3"
            style={{
              fontFamily: "'Cormorant Garamond', serif",
              fontWeight: 600,
              fontSize: "10.5px",
              letterSpacing: "0.22em",
              textTransform: "uppercase",
              color: "rgba(11, 42, 90, 0.45)",
            }}
          >
            <span style={{ color: "#b8860b", textShadow: "0 0 6px rgba(240,194,127,0.5)" }}>✦</span>
            {"  "}Find Your Top Talent
          </div>
        </footer>
      </main>
    </div>
  );
}

/* ─── Section label helper ───────────────────────────────────────── */

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <h2
      className="flex items-center justify-center gap-2 text-center"
      style={{
        fontFamily: "'Cormorant Garamond', serif",
        fontWeight: 600,
        fontSize: "11.5px",
        letterSpacing: "0.22em",
        textTransform: "uppercase",
        color: "#b8860b",
      }}
    >
      <span aria-hidden="true" style={{ textShadow: "0 0 8px rgba(240,194,127,0.55)", fontSize: "10px" }}>✦</span>
      {children}
    </h2>
  );
}
