// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-equilibrium-state.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_equilibrium_state_default = defineTool({
  name: "get_equilibrium_state",
  title: "Get Equilibrium state",
  description: "Return the signed-in user's Equilibrium snapshot: state row, strategies, workstreams with active tasks, focus tasks, and recent synthesis log.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [state, strategies, workstreams, focus, synthesisLog] = await Promise.all([
      supabase.from("equilibrium_state").select("*").eq("user_id", userId).maybeSingle(),
      supabase.from("equilibrium_strategies").select("*").eq("user_id", userId).order("position", { ascending: true }),
      supabase.from("equilibrium_workstreams").select("*").eq("user_id", userId).order("position", { ascending: true }),
      supabase.from("equilibrium_focus").select("*").eq("user_id", userId).order("position", { ascending: true }),
      supabase.from("equilibrium_synthesis_log").select("*").eq("user_id", userId).order("generated_at", { ascending: false }).limit(5)
    ]);
    const workstreamRows = workstreams.data ?? [];
    const workstreamIds = workstreamRows.map((row) => row.id).filter(Boolean);
    const tasksResult = workstreamIds.length ? await supabase.from("equilibrium_tasks").select("*").in("workstream_id", workstreamIds).order("position", { ascending: true }) : { data: [], error: null };
    const taskRows = tasksResult.data ?? [];
    const focusRows = focus.data ?? [];
    const focusIds = new Set(focusRows.map((row) => row.task_id));
    const activeTasks = taskRows.filter((t) => t.status !== "done");
    const payload = {
      user_id: userId,
      state: state.data ?? null,
      strategies: strategies.data ?? [],
      workstreams: workstreamRows.map((ws) => ({
        ...ws,
        active_tasks: activeTasks.filter((t) => t.workstream_id === ws.id)
      })),
      focus: focusRows,
      focus_tasks: activeTasks.filter((t) => focusIds.has(t.id)),
      synthesis_log: synthesisLog.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-game-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_game_profile_default = defineTool2({
  name: "get_game_profile",
  title: "Get game profile",
  description: "Return the signed-in user's game profile: mission statement, last ZoG snapshot id, and recent update timestamps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("game_profiles").select("mission_statement, last_zog_snapshot_id, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jypjttotvastdhanwvrx";
var mcp_default = defineMcp({
  name: "genius-business-mcp",
  title: "Genius Business MCP",
  version: "0.1.0",
  instructions: "Read tools for the signed-in user's Genius Business state. Use `get_equilibrium_state` for strategies/workstreams/focus tasks, and `get_game_profile` for the mission statement.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_equilibrium_state_default, get_game_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
