-- Public profile usernames
--
-- Guarantees:
--   * every claimed/authenticated profile receives a stable public username;
--   * generated fallbacks never expose or encode the user's email address;
--   * usernames are canonical lowercase URL slugs and unique case-insensitively;
--   * reserved application routes cannot be claimed;
--   * a user can change only their own username through a narrow RPC.

create or replace function public.normalize_profile_username(p_value text)
returns text
language sql
immutable
strict
set search_path = public
as $$
  select trim(both '-' from regexp_replace(
    regexp_replace(
      lower(translate(
        p_value,
        'àáâãäåæçèéêëìíîïñòóôõöøœùúûüýÿšž',
        'aaaaaaaceeeeiiiinooooooouuuuyysz'
      )),
      '[^a-z0-9]+', '-', 'g'
    ),
    '-{2,}', '-', 'g'
  ));
$$;

comment on function public.normalize_profile_username(text) is
  'Canonicalizes a proposed public-profile username to a lowercase URL slug.';

create or replace function public.profile_username_is_reserved(p_username text)
returns boolean
language sql
immutable
strict
set search_path = public
as $$
  select p_username = any (array[
    -- Current top-level application routes plus conventional infrastructure
    -- routes. Keep this list additive whenever a new root route ships.
    '1-pager', '27', 'about', 'account', 'activate', 'activate-top-talent',
    'activations', 'admin', 'ai-os', 'ai-upgrade', 'alexander',
    'api', 'app', 'art', 'asset-mapping', 'auth', 'blog', 'build', 'callback',
    'canvas', 'character', 'cockpit', 'codex', 'collaborate', 'communities',
    'community', 'connections', 'contact', 'dashboard', 'destiny', 'docs',
    'dossier', 'equilibrium', 'events', 'explore', 'favicon', 'feedback',
    'fmf', 'founder', 'founder-market-fit', 'founders', 'game', 'genius-admin',
    'genius-layer-matching', 'genius-offer', 'genius-offer-intake', 'grow',
    'growth-paths', 'help', 'hero', 'holomap', 'home', 'ignite',
    'integral-theory-upgrade1', 'integralevolution', 'intelligences', 'intros',
    'karime', 'landing', 'legal', 'library', 'login', 'logout', 'm',
    'manifesto', 'map', 'marketplace', 'mdls-preview', 'me', 'mens-circle',
    'mission-discovery', 'missions', 'modules', 'monetization', 'mp',
    'my-artifacts', 'my-page', 'my-result', 'onboarding', 'oyi', 'p', 'page',
    'path', 'playbook', 'preview', 'privacy', 'product', 'product-builder',
    'products', 'profile', 'prompt', 'proposalforwegoodovahere',
    'quality-of-life-map', 'quiz', 'resources', 'reveal', 'robots', 'sandra',
    'sergey', 'settings', 'sign-in', 'sign-up', 'sitemap', 'skills', 'sohn',
    'spaces', 'start', 'support', 'terms', 'the-originals', 'today', 'tools',
    'transcriber', 'u', 'ubb', 'ubd', 'ubl', 'web3', 'you', 'zone-of-genius'
  ]::text[]);
$$;

create or replace function public.profile_username_is_valid(p_username text)
returns boolean
language sql
immutable
strict
set search_path = public
as $$
  select p_username ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'
    and p_username !~ '--'
    and not public.profile_username_is_reserved(p_username);
$$;

comment on function public.profile_username_is_valid(text) is
  'True for canonical, non-reserved profile usernames between 3 and 40 characters.';

-- Resolve any legacy case-only collisions before adding the case-insensitive index.
-- The oldest profile keeps the readable username; later duplicates receive an opaque
-- suffix. No email-derived material is used.
with ranked as (
  select id,
         username,
         row_number() over (
           partition by lower(username)
           order by created_at asc, id asc
         ) as duplicate_number
  from public.game_profiles
  where username is not null
)
update public.game_profiles gp
set username = left(public.normalize_profile_username(r.username), 31)
               || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)
from ranked r
where gp.id = r.id
  and r.duplicate_number > 1;

-- Invalid legacy usernames are regenerated by the backfill below.
update public.game_profiles
set username = null
where username is not null
  and not public.profile_username_is_valid(
    public.normalize_profile_username(username)
  );

drop index if exists public.idx_game_profiles_username;
create unique index if not exists idx_game_profiles_username_lower_unique
  on public.game_profiles (lower(username))
  where username is not null;

-- Preserve the founder's canonical short URL. This identity match is based only
-- on public name fields and does not bake a private email address into the schema.
with founder_profile as (
  select id
  from public.game_profiles
  where lower(coalesce(first_name, '')) in ('aleksandr', 'alexander')
    and lower(coalesce(last_name, '')) = 'konstantinov'
  order by created_at asc, id asc
  limit 1
)
update public.game_profiles gp
set username = 'aleksandr'
from founder_profile fp
where gp.id = fp.id
  and not exists (
    select 1 from public.game_profiles existing
    where lower(existing.username) = 'aleksandr'
      and existing.id <> gp.id
  );

create or replace function public.generate_profile_username(
  p_first_name text,
  p_last_name text,
  p_profile_id uuid default null
)
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_base text;
  v_candidate text;
  v_attempt integer := 0;
begin
  -- Names are intentionally the only human-readable source. If no usable name is
  -- available, use cryptographic randomness rather than the email local-part.
  v_base := public.normalize_profile_username(
    concat_ws('-', nullif(trim(p_first_name), ''), nullif(trim(p_last_name), ''))
  );

  if length(v_base) < 3 or public.profile_username_is_reserved(v_base) then
    v_base := 'member';
  end if;
  v_base := left(v_base, 31);

  -- Serialize generation for the same readable base. Without this lock, two
  -- same-name signups could both observe the base as free before either inserts.
  perform pg_advisory_xact_lock(hashtextextended('profile-username:' || v_base, 0));

  loop
    v_candidate := case
      when v_attempt = 0 and v_base <> 'member' then v_base
      else v_base || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)
    end;

    if not exists (
      select 1
      from public.game_profiles gp
      where lower(gp.username) = lower(v_candidate)
        and (p_profile_id is null or gp.id <> p_profile_id)
    ) and public.profile_username_is_valid(v_candidate) then
      return v_candidate;
    end if;

    v_attempt := v_attempt + 1;
    if v_attempt >= 20 then
      raise exception 'Could not generate a unique profile username'
        using errcode = 'unique_violation';
    end if;
  end loop;
end;
$$;

revoke all on function public.generate_profile_username(text, text, uuid) from public;

create or replace function public.ensure_profile_username()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.username is not null then
    new.username := public.normalize_profile_username(new.username);
    if not public.profile_username_is_valid(new.username) then
      raise exception 'Username must be 3-40 characters using lowercase letters, numbers, or single hyphens, and must not be reserved.'
        using errcode = 'check_violation';
    end if;
  end if;

  -- Anonymous/local profiles do not need a public URL. The trigger fills the slug
  -- as soon as ownership is attached, as well as on ordinary authenticated inserts.
  if new.user_id is not null and new.username is null then
    new.username := public.generate_profile_username(
      new.first_name,
      new.last_name,
      new.id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists ensure_game_profile_username on public.game_profiles;
create trigger ensure_game_profile_username
before insert or update of user_id, first_name, last_name, username
on public.game_profiles
for each row execute function public.ensure_profile_username();

-- Existing claimed profiles get usernames immediately. This intentionally does not
-- inspect auth.users.email, so an email can never be reconstructed from the result.
update public.game_profiles
set username = public.generate_profile_username(first_name, last_name, id)
where user_id is not null
  and username is null;

create or replace function public.set_my_public_profile_username(p_username text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text := public.normalize_profile_username(p_username);
  v_updated text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = 'insufficient_privilege';
  end if;
  if not public.profile_username_is_valid(v_username) then
    raise exception 'Username must be 3-40 characters using letters, numbers, or single hyphens, and must not be reserved.'
      using errcode = 'check_violation';
  end if;

  update public.game_profiles
  set username = v_username
  where user_id = auth.uid()
  returning username into v_updated;

  if v_updated is null then
    raise exception 'Profile not found' using errcode = 'no_data_found';
  end if;
  return v_updated;
exception
  when unique_violation then
    raise exception 'That username is already taken' using errcode = 'unique_violation';
end;
$$;

revoke all on function public.set_my_public_profile_username(text) from public;
grant execute on function public.set_my_public_profile_username(text) to authenticated;

comment on function public.set_my_public_profile_username(text) is
  'Validates and changes the authenticated user''s public profile username.';

-- Public pages must not SELECT game_profiles directly: that table contains email,
-- access tokens, entitlement state, and other private fields. This projection is
-- deliberately narrow and enforces both the audience gate (who may see it) and
-- content-depth setting (how much they may see) inside the database.
create or replace function public.get_public_profile_by_username(p_username text)
returns table (
  user_id uuid,
  username text,
  first_name text,
  last_name text,
  avatar_url text,
  location text,
  visibility text,
  show_location boolean,
  show_mission boolean,
  show_offer boolean,
  appleseed_data jsonb,
  excalibur_data jsonb,
  top_three_talents jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  select
    gp.user_id,
    gp.username,
    gp.first_name,
    gp.last_name,
    gp.avatar_url,
    case when coalesce(gp.show_location, true) then gp.location else null end,
    coalesce(gp.visibility, 'full'),
    gp.show_location,
    gp.show_mission,
    gp.show_offer,
    case
      when coalesce(gp.visibility, 'full') <> 'hidden'
        then zs.appleseed_data
      else null
    end,
    case
      when coalesce(gp.visibility, 'full') = 'full'
        and coalesce(gp.show_offer, true)
        then zs.excalibur_data
      else null
    end,
    case
      when coalesce(gp.visibility, 'full') <> 'hidden'
        then zs.top_three_talents
      else null
    end
  from public.game_profiles gp
  left join public.zog_snapshots zs on zs.id = gp.last_zog_snapshot_id
  where lower(gp.username) = lower(public.normalize_profile_username(p_username))
    and (
      -- Owners can always preview their own profile, including hidden profiles.
      gp.user_id = auth.uid()
      or (
        coalesce(gp.visibility, 'full') <> 'hidden'
        and (
          coalesce(gp.profile_visibility, 'public') = 'public'
          or (
            gp.profile_visibility = 'friends'
            and auth.uid() is not null
            and exists (
              select 1 from public.match_intros mi
              where (mi.user_a_id = auth.uid() and mi.user_b_id = gp.user_id)
                 or (mi.user_b_id = auth.uid() and mi.user_a_id = gp.user_id)
            )
          )
          or (
            gp.profile_visibility = 'communities'
            and auth.uid() is not null
            and exists (
              select 1 from public.community_members cm
              where cm.user_id = auth.uid()
                and cm.community_id = any(gp.visible_community_ids)
            )
          )
        )
      )
    )
  limit 1;
$$;

revoke all on function public.get_public_profile_by_username(text) from public;
grant execute on function public.get_public_profile_by_username(text) to anon, authenticated;

comment on function public.get_public_profile_by_username(text) is
  'Privacy-safe public profile projection. Enforces audience and content-depth visibility without exposing game_profiles private columns.';
