-- Product Builder Schema Migration
-- Created: January 24, 2026
-- Purpose: Support the Product Builder module

-- Table for storing product builder progress and snapshots
CREATE TABLE IF NOT EXISTS product_builder_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Deep content (generated by AI, stored as JSON)
  deep_icp JSONB,
  deep_pain JSONB,
  deep_tp JSONB,
  landing_content JSONB,
  blueprint_content JSONB,
  cta_config JSONB,
  
  -- Resonance ratings for each step
  resonance_ratings JSONB DEFAULT '{}',
  
  -- Status
  current_step INTEGER DEFAULT 0,
  is_complete BOOLEAN DEFAULT FALSE,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for published marketplace products
CREATE TABLE IF NOT EXISTS marketplace_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  snapshot_id UUID REFERENCES product_builder_snapshots(id) ON DELETE SET NULL,
  
  -- Product identifiers
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  
  -- Content
  landing_html TEXT,
  blueprint_content JSONB,
  cta_config JSONB,
  
  -- Metadata
  is_live BOOLEAN DEFAULT FALSE,
  views INTEGER DEFAULT 0,
  
  -- Timestamps
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_product_builder_snapshots_user_id 
  ON product_builder_snapshots(user_id);
  
CREATE INDEX IF NOT EXISTS idx_marketplace_products_user_id 
  ON marketplace_products(user_id);
  
CREATE INDEX IF NOT EXISTS idx_marketplace_products_slug 
  ON marketplace_products(slug);
  
CREATE INDEX IF NOT EXISTS idx_marketplace_products_is_live 
  ON marketplace_products(is_live) WHERE is_live = TRUE;

-- Enable RLS
ALTER TABLE product_builder_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_products ENABLE ROW LEVEL SECURITY;

-- RLS Policies for product_builder_snapshots
CREATE POLICY "Users can view own snapshots" 
  ON product_builder_snapshots FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own snapshots" 
  ON product_builder_snapshots FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own snapshots" 
  ON product_builder_snapshots FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own snapshots" 
  ON product_builder_snapshots FOR DELETE 
  USING (auth.uid() = user_id);

-- RLS Policies for marketplace_products
CREATE POLICY "Anyone can view live products" 
  ON marketplace_products FOR SELECT 
  USING (is_live = TRUE OR auth.uid() = user_id);

CREATE POLICY "Users can insert own products" 
  ON marketplace_products FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own products" 
  ON marketplace_products FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own products" 
  ON marketplace_products FOR DELETE 
  USING (auth.uid() = user_id);

-- Function to auto-update updated_at
CREATE OR REPLACE FUNCTION update_product_builder_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER product_builder_snapshots_updated_at
  BEFORE UPDATE ON product_builder_snapshots
  FOR EACH ROW
  EXECUTE FUNCTION update_product_builder_updated_at();

CREATE TRIGGER marketplace_products_updated_at
  BEFORE UPDATE ON marketplace_products
  FOR EACH ROW
  EXECUTE FUNCTION update_product_builder_updated_at();